import type { Metadata } from "next";
import { DynaPuff, Noto_Sans } from "next/font/google";

import "./globals.css";

import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Providers from "./providers";

const dinaPuffInit = DynaPuff({
  subsets: ["latin"],
  weight: ["600"],
  variable: "--font-dina-puff",
});

const notoSansfInit = Noto_Sans({
  subsets: ["latin"],
  weight: ["400", "600"],
  variable: "--font-noto-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dinaPuffInit.variable} ${notoSansfInit.variable} antialiased`}
      >
        <Header />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
